# 데이터 불러오기

In [73]:
file_path = r"C:\Users\james\Documents\GitHub\Traffic_Volume_Prediction"

In [74]:
# 데이터 불러오기
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

total = pd.read_csv(file_path + r"\Data\refined_data.csv")
total

,일자,Hour,1005004000_velocity,1050003300_velocity,1050020400_velocity,1070000200_velocity,1070000500_velocity,1070001600_velocity,D-08 유입_traffic,D-08 유출_traffic,F-03 유입_traffic,F-04 유출_traffic,기온(°C),강수량(mm),풍속(m/s),습도(%),적설(cm)
0,20220419,1,39.82,73.83,18.79,76.42,66.08,90.92,550.0,712.0,1079.0,969.0,11.4,NaN,1.4,63.0,NaN
1,20220419,2,42.19,76.08,14.66,75.08,68.00,92.50,380.0,625.0,829.0,828.0,11.0,NaN,1.3,68.0,NaN
2,20220419,3,43.04,75.50,16.46,74.25,66.50,92.08,410.0,495.0,689.0,709.0,10.4,NaN,1.7,69.0,NaN
3,20220419,4,34.34,74.42,18.91,76.67,67.42,89.83,624.0,709.0,1020.0,1011.0,10.1,NaN,1.0,72.0,NaN
4,20220419,5,35.92,75.83,20.45,76.17,66.83,90.50,1275.0,1222.0,2463.0,2526.0,9.7,NaN,1.1,74.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20758,20240831,20,29.76,73.92,21.85,54.08,64.50,50.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20759,20240831,21,28.94,74.42,21.24,65.00,63.67,60.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20760,20240831,22,29.84,76.17,22.67,56.75,63.00,44.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20761,20240831,23,29.66,75.92,23.95,64.50,63.92,54.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20762,20240831,24,32.22,81.75,20.83,68.83,64.92,69.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
import pandas as pd

# 데이터 로드
csv = pd.read_csv(r"C:\Users\james\Documents\카카오톡 받은 파일\traffic_data_processed_all.csv")

# 결측치 비율 계산
missing_ratios = csv.isnull().mean()  # 각 열의 결측치 비율 계산

# 5% 미만인 열 필터링
columns_to_keep = missing_ratios[missing_ratios < 0.01].index  # 결측치 비율이 10% 미만인 열 이름
csv = csv[columns_to_keep]  # 필터링된 데이터프레임

# 결과 출력
print(f"총 {len(columns_to_keep)}개의 열이 남았습니다.")

총 49개의 열이 남았습니다.

In [76]:

# csv = csv[["일자", "Hour", "A-01 유입_traffic", "A-01 유출_traffic", "A-05 유입_traffic" , "A-05 유출_traffic", "A-06 유입_traffic", "A-06 유출_traffic"]]

In [77]:
total = total.merge(csv, how = "left", on = ["일자", "Hour"])
total

,일자,Hour,1005004000_velocity,1050003300_velocity,1050020400_velocity,1070000200_velocity,1070000500_velocity,1070001600_velocity,D-08 유입_traffic,D-08 유출_traffic,...,F-05 유출_traffic,F-06 유입_traffic,F-07 유입_traffic,F-07 유출_traffic,F-08 유입_traffic,F-08 유출_traffic,F-09 유입_traffic,F-09 유출_traffic,F-10 유입_traffic,F-10 유출_traffic
0,20220419,1,39.82,73.83,18.79,76.42,66.08,90.92,550.0,712.0,...,1807.0,1554.0,876.0,968.0,201.0,392.0,20.0,29.0,95.0,263.0
1,20220419,2,42.19,76.08,14.66,75.08,68.00,92.50,380.0,625.0,...,1311.0,1146.0,755.0,707.0,152.0,251.0,18.0,18.0,39.0,149.0
2,20220419,3,43.04,75.50,16.46,74.25,66.50,92.08,410.0,495.0,...,1041.0,1081.0,669.0,602.0,144.0,190.0,17.0,18.0,61.0,96.0
3,20220419,4,34.34,74.42,18.91,76.67,67.42,89.83,624.0,709.0,...,1074.0,1379.0,800.0,840.0,234.0,259.0,27.0,48.0,132.0,96.0
4,20220419,5,35.92,75.83,20.45,76.17,66.83,90.50,1275.0,1222.0,...,1898.0,3106.0,1949.0,2540.0,1244.0,618.0,404.0,396.0,862.0,194.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20758,20240831,20,29.76,73.92,21.85,54.08,64.50,50.58,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20759,20240831,21,28.94,74.42,21.24,65.00,63.67,60.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20760,20240831,22,29.84,76.17,22.67,56.75,63.00,44.42,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20761,20240831,23,29.66,75.92,23.95,64.50,63.92,54.75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20762,20240831,24,32.22,81.75,20.83,68.83,64.92,69.17,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## train, test 분리

In [78]:
total['Year'] = total['일자'].astype(str).str[:4].astype(int)
total['Month'] = total['일자'].astype(str).str[4:6].astype(int)
total['Day'] = total['일자'].astype(str).str[6:8].astype(int)

print(total[['일자', 'Year', 'Month', 'Day']].head())

         일자  Year  Month  Day
0  20220419  2022      4   19
1  20220419  2022      4   19
2  20220419  2022      4   19
3  20220419  2022      4   19
4  20220419  2022      4   19

In [79]:
total = total[~(((total['Year'] == 2024) & (total['Month'] == 8)) | ((total['Year'] == 2024) & (total['Month'] == 7)  & (total['Day'] == 31)))]
total.tail()

,일자,Hour,1005004000_velocity,1050003300_velocity,1050020400_velocity,1070000200_velocity,1070000500_velocity,1070001600_velocity,D-08 유입_traffic,D-08 유출_traffic,...,F-07 유출_traffic,F-08 유입_traffic,F-08 유출_traffic,F-09 유입_traffic,F-09 유출_traffic,F-10 유입_traffic,F-10 유출_traffic,Year,Month,Day
20000,20240730,20,22.97,7.25,20.47,18.42,41.92,44.75,NaN,NaN,...,3259.0,1581.0,2728.0,1314.0,1345.0,863.0,2167.0,2024,7,30
20001,20240730,21,25.02,58.92,23.60,37.42,62.50,44.92,NaN,NaN,...,3206.0,1330.0,1840.0,763.0,782.0,763.0,1819.0,2024,7,30
20002,20240730,22,30.20,76.67,21.85,55.67,63.50,49.58,NaN,NaN,...,2539.0,1158.0,1753.0,434.0,612.0,629.0,1792.0,2024,7,30
20003,20240730,23,30.19,75.42,19.79,60.17,65.00,56.08,NaN,NaN,...,2082.0,667.0,1052.0,188.0,303.0,432.0,1131.0,2024,7,30
20004,20240730,24,31.66,83.17,22.12,68.25,63.83,70.17,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,7,30

In [80]:
total.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20005 entries, 0 to 20004
Data columns (total 67 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   일자                   20005 non-null  int64
 1   Hour                 20005 non-null  int64
 2   1005004000_velocity  20005 non-null  float64
 3   1050003300_velocity  19970 non-null  float64
 4   1050020400_velocity  20005 non-null  float64
 5   1070000200_velocity  19972 non-null  float64
 6   1070000500_velocity  19972 non-null  float64
 7   1070001600_velocity  19959 non-null  float64
 8   D-08 유입_traffic      13012 non-null  float64
 9   D-08 유출_traffic      13018 non-null  float64
 10  F-03 유입_traffic_x    19292 non-null  float64
 11  F-04 유출_traffic_x    19304 non-null  float64
 12  기온(°C)               20005 non-null  float64
 13  강수량(mm)              2538 non-null   float64
 14  풍속(m/s)              19937 non-null  float64
 15  습도(%)                20005 non-null  float64
 16  적설(cm)               848 non-null    float64
 17  A-12 유입_traffic      19118 non-null  float64
 18  A-19 유입_traffic      19034 non-null  float64
 19  A-20 유입_traffic      19104 non-null  float64
 20  A-22 유입_traffic      19094 non-null  float64
 21  A-22 유출_traffic      19105 non-null  float64
 22  B-01 유입_traffic      19102 non-null  float64
 23  B-06 유입_traffic      19069 non-null  float64
 24  B-14 유입_traffic      19142 non-null  float64
 25  B-14 유출_traffic      19114 non-null  float64
 26  B-22 유입_traffic      19036 non-null  float64
 27  B-22 유출_traffic      19032 non-null  float64
 28  B-36 유출_traffic      19064 non-null  float64
 29  C-02 유입_traffic      19074 non-null  float64
 30  C-06 유입_traffic      19039 non-null  float64
 31  C-07 유입_traffic      19011 non-null  float64
 32  C-09 유출_traffic      19044 non-null  float64
 33  C-17 유입_traffic      19044 non-null  float64
 34  C-17 유출_traffic      19079 non-null  float64
 35  C-20 유입_traffic      19082 non-null  float64
 36  C-21 유출_traffic      18985 non-null  float64
 37  D-04 유입_traffic      19129 non-null  float64
 38  D-12 유출_traffic      19077 non-null  float64
 39  D-16 유출_traffic      19125 non-null  float64
 40  D-17 유입_traffic      19061 non-null  float64
 41  D-17 유출_traffic      19040 non-null  float64
 42  D-21 유출_traffic      19004 non-null  float64
 43  D-28 유입_traffic      19062 non-null  float64
 44  D-28 유출_traffic      19062 non-null  float64
 45  D-31 유입_traffic      19008 non-null  float64
 46  D-35 유입_traffic      19078 non-null  float64
 47  D-35 유출_traffic      19100 non-null  float64
 48  D-44 유출_traffic      19087 non-null  float64
 49  F-02 유출_traffic      19001 non-null  float64
 50  F-03 유입_traffic_y    19135 non-null  float64
 51  F-03 유출_traffic      19159 non-null  float64
 52  F-04 유출_traffic_y    19145 non-null  float64
 53  F-05 유입_traffic      19075 non-null  float64
 54  F-05 유출_traffic      19076 non-null  float64
 55  F-06 유입_traffic      19109 non-null  float64
 56  F-07 유입_traffic      19111 non-null  float64
 57  F-07 유출_traffic      19154 non-null  float64
 58  F-08 유입_traffic      19172 non-null  float64
 59  F-08 유출_traffic      19172 non-null  float64
 60  F-09 유입_traffic      19164 non-null  float64
 61  F-09 유출_traffic      19166 non-null  float64
 62  F-10 유입_traffic      19170 non-null  float64
 63  F-10 유출_traffic      19168 non-null  float64
 64  Year                 20005 non-null  int32
 65  Month                20005 non-null  int32
 66  Day                  20005 non-null  int32
dtypes: float64(62), int32(3), int64(2)
memory usage: 10.1 MB

In [81]:
total.isnull().sum()

일자                       0
Hour                     0
1005004000_velocity      0
1050003300_velocity     35
1050020400_velocity      0
                      ...
F-10 유입_traffic        835
F-10 유출_traffic        837
Year                     0
Month                    0
Day                      0
Length: 67, dtype: int64

In [82]:
train = total[~((total['Year'] == 2024) & (total['Month'] == 7))]
test = total[((total['Year'] == 2024) & (total['Month'] == 7))]
print(train.shape, test.shape)

(19285, 67) (720, 67)

# Feature Engineering

## 파생변수 추가

In [83]:
import holidays
import numpy as np

dfs = [train, test]

for df in dfs:
    df['일자'] = pd.to_datetime(df['일자'], format='%Y%m%d')

    # 1. 주말 여부 추가
    df['is_weekend'] = df['일자'].dt.dayofweek >= 5  # 토요일(5) 또는 일요일(6)일 경우 True

    # 2. 공휴일 여부 추가 (한국 공휴일 기준)
    kr_holidays = holidays.KR(years=df['Year'].unique())  # 한국 공휴일
    df['is_holiday'] = df['일자'].isin(kr_holidays)

    # 3. 출퇴근 시간 7~9, 17~19
    df['is_morning_rush'] = df['Hour'].between(7, 9)
    df['is_evening_rush'] = df['Hour'].between(17, 19)

    # 4. 주기성 인식(Day는 drop)
    # 4.1. 월 주기성 추가 (1월~12월)
    df['month_sin'] = np.sin(2 * np.pi * df['Month'] / 12)
    df['month_cos'] = np.cos(2 * np.pi * df['Month'] / 12)

    # 4.2. 시간 주기성 추가 (0시~23시)
    df['hour_sin'] = np.sin(2 * np.pi * df['Hour'] / 24)
    df['hour_cos'] = np.cos(2 * np.pi * df['Hour'] / 24)

    print(df.shape)

(19285, 75)
(720, 75)

## encoding

In [84]:
one_hot_columns = [
  #  "season"
]

if one_hot_columns:
    combined = pd.concat([train, test], keys=['train', 'test']).reset_index(level=0).rename(columns={'level_0': 'source'})

    one_hot_columns = ["season"]
    for column in one_hot_columns:
        combined = pd.get_dummies(combined, columns=[column], prefix=f'{column}')

    train = combined[combined['source'] == 'train'].drop(columns=['source'])
    test = combined[combined['source'] == 'test'].drop(columns=['source'])

In [85]:
train.columns

Index(['일자', 'Hour', '1005004000_velocity', '1050003300_velocity',
       '1050020400_velocity', '1070000200_velocity', '1070000500_velocity',
       '1070001600_velocity', 'D-08 유입_traffic', 'D-08 유출_traffic',
       'F-03 유입_traffic_x', 'F-04 유출_traffic_x', '기온(°C)', '강수량(mm)',
       '풍속(m/s)', '습도(%)', '적설(cm)', 'A-12 유입_traffic', 'A-19 유입_traffic',
       'A-20 유입_traffic', 'A-22 유입_traffic', 'A-22 유출_traffic',
       'B-01 유입_traffic', 'B-06 유입_traffic', 'B-14 유입_traffic',
       'B-14 유출_traffic', 'B-22 유입_traffic', 'B-22 유출_traffic',
       'B-36 유출_traffic', 'C-02 유입_traffic', 'C-06 유입_traffic',
       'C-07 유입_traffic', 'C-09 유출_traffic', 'C-17 유입_traffic',
       'C-17 유출_traffic', 'C-20 유입_traffic', 'C-21 유출_traffic',
       'D-04 유입_traffic', 'D-12 유출_traffic', 'D-16 유출_traffic',
       'D-17 유입_traffic', 'D-17 유출_traffic', 'D-21 유출_traffic',
       'D-28 유입_traffic', 'D-28 유출_traffic', 'D-31 유입_traffic',
       'D-35 유입_traffic', 'D-35 유출_traffic', 'D-44 유출_traffic',
       'F-02 유출_traffic', 'F-03 유입_traffic_y', 'F-03 유출_traffic',
       'F-04 유출_traffic_y', 'F-05 유입_traffic', 'F-05 유출_traffic',
       'F-06 유입_traffic', 'F-07 유입_traffic', 'F-07 유출_traffic',
       'F-08 유입_traffic', 'F-08 유출_traffic', 'F-09 유입_traffic',
       'F-09 유출_traffic', 'F-10 유입_traffic', 'F-10 유출_traffic', 'Year',
       'Month', 'Day', 'is_weekend', 'is_holiday', 'is_morning_rush',
       'is_evening_rush', 'month_sin', 'month_cos', 'hour_sin', 'hour_cos'],
      dtype='object')

## column drop

In [86]:
drop_columns=[
    '일자',
    'Month',
    'Day',
    'Hour',
    'D-08 유입_traffic',
    'D-08 유출_traffic'
]

train = train.copy()
test = test.copy()

for column in drop_columns:
    if column in train.columns:
        train.drop(columns=column, inplace=True)
        test.drop(columns=column, inplace=True)
        print(f"(column명: {column})를 drop했습니다.")

(column명: 일자)를 drop했습니다.
(column명: Month)를 drop했습니다.
(column명: Day)를 drop했습니다.
(column명: Hour)를 drop했습니다.
(column명: D-08 유입_traffic)를 drop했습니다.
(column명: D-08 유출_traffic)를 drop했습니다.

In [87]:
train

,1005004000_velocity,1050003300_velocity,1050020400_velocity,1070000200_velocity,1070000500_velocity,1070001600_velocity,F-03 유입_traffic_x,F-04 유출_traffic_x,기온(°C),강수량(mm),...,F-10 유출_traffic,Year,is_weekend,is_holiday,is_morning_rush,is_evening_rush,month_sin,month_cos,hour_sin,hour_cos
0,39.82,73.83,18.79,76.42,66.08,90.92,1079.0,969.0,11.4,NaN,...,263.0,2022,False,False,False,False,8.660254e-01,-0.5,2.588190e-01,0.965926
1,42.19,76.08,14.66,75.08,68.00,92.50,829.0,828.0,11.0,NaN,...,149.0,2022,False,False,False,False,8.660254e-01,-0.5,5.000000e-01,0.866025
2,43.04,75.50,16.46,74.25,66.50,92.08,689.0,709.0,10.4,NaN,...,96.0,2022,False,False,False,False,8.660254e-01,-0.5,7.071068e-01,0.707107
3,34.34,74.42,18.91,76.67,67.42,89.83,1020.0,1011.0,10.1,NaN,...,96.0,2022,False,False,False,False,8.660254e-01,-0.5,8.660254e-01,0.500000
4,35.92,75.83,20.45,76.17,66.83,90.50,2463.0,2526.0,9.7,NaN,...,194.0,2022,False,False,False,False,8.660254e-01,-0.5,9.659258e-01,0.258819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19280,31.38,80.67,22.44,67.08,66.33,60.58,3252.0,2777.0,24.5,NaN,...,1527.0,2024,True,False,False,False,1.224647e-16,-1.0,-8.660254e-01,0.500000
19281,33.93,75.42,24.49,64.83,65.92,60.67,3456.0,2788.0,23.8,NaN,...,1571.0,2024,True,False,False,False,1.224647e-16,-1.0,-7.071068e-01,0.707107
19282,34.50,73.33,21.62,65.67,65.92,59.00,2961.0,2466.0,23.1,NaN,...,1258.0,2024,True,False,False,False,1.224647e-16,-1.0,-5.000000e-01,0.866025
19283,33.01,75.25,24.05,66.58,65.58,68.25,2094.0,1696.0,22.8,NaN,...,689.0,2024,True,False,False,False,1.224647e-16,-1.0,-2.588190e-01,0.965926
19284,32.69,78.08,22.49,70.25,67.17,73.42,1644.0,1498.0,24.4,3.5,...,NaN,2024,True,False,False,False,1.224647e-16,-1.0,-2.449294e-16,1.000000

In [88]:
# 데이터프레임을 CSV 파일로 저장
file_name = r"\Data\train.csv"
train.to_csv(file_path+file_name, index=False)

file_name = r"\Data\test.csv"
test.to_csv(file_path+file_name, index=False)

In [89]:
csv.shape

(20472, 49)